/*
 * generated by Xtext 2.10.0
 */
package org.example.domainmodel.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.example.domainmodel.domainmodel.Domainmodel
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DomainmodelInjectorProvider)
class DomainmodelParsingTest{

	@Inject
	ParseHelper<Domainmodel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			package my.company.blog {
						  
			    import my.company.common.*
			    
			    entity Blog {
			        title: String
			        many posts: Post
			    }
			    
			    entity Post extends my.company.common.HasAuthor {
			        title: String
			        content: String
			        many comments: Comment
			    }
			    
			    entity Comment extends HasAuthor {
			        content: String
			    }
			}
		''')
		Assert.assertNotNull(result)
	}

}
